### ISSUE TITLE
Email, Mail and Text

### ISSUE THREAD

**Issue by FMGstaff** [fraternity-management-group/gms#26] opened 2021-03-02 04:21 UTC
The check boxes under contacts should be Email, Mail, Phone and Text

![Mail Text Email](https://user-images.githubusercontent.com/74945938/109596707-04602f80-7ad4-11eb-90ca-7246e1a93623.PNG)

**Comment by jdfergason** [comment] 2021-03-05 00:49
Duplicate of #24

**Closed by jdfergason** 2021-03-05 00:49 UTC
Labels: duplicate
